[project]
name = "ocr"
version = "0.1.0"
description = ""
authors = [
    {name = "Ruben Costa",email = "rubenlavoscosta@gmail.com"},
    {name = "Miguel Dias",email = "miguelpintodias@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "torch (>=2.13.0,<3.0.0)",
    "torchvision (>=0.28.0,<0.29.0)",
    "opencv-python (==4.12.0.88)",
    "numpy (>=2,<2.3)",
    "pillow (>=12.3.0,<13.0.0)",
    "matplotlib (>=3.11.0,<4.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "label-studio-sdk (>=2.0.23,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
